local EquipmentGenerator = require("src.EquipmentGenerator")

describe("EquipmentGenerator", function()
    it("returns a matching rarity when available", function()
        math.randomseed(1)
        local item = EquipmentGenerator.getRandomItem("Hat", "A")
        assert.is_table(item)
        assert.equals("Hat", item.slot)
        assert.equals("A", item.rarity)
    end)

    it("falls back to any item when rarity missing", function()
        local item = EquipmentGenerator.getRandomItem("Hat", "Non")
        assert.is_table(item)
        assert.equals("Hat", item.slot)
    end)
end)
