local InventoryUISystem = require("src.InventoryUISystem")
local ItemSystem = require("src.ItemSystem")

describe("InventoryUISystem", function()
    it("toggles and refreshes items", function()
        local items = ItemSystem.new()
        table.insert(items.inventory, {name = "Sword"})
        table.insert(items.inventory, {name = "Shield"})
        local ui = InventoryUISystem.new(items)
        ui:toggle()
        assert.is_true(ui._open)
        assert.equals(2, #ui._container:GetChildren())
        ui:toggle()
        assert.is_false(ui._open)
    end)
end)
