local ItemSystem = require("../src/ItemSystem")

describe("ItemSystem", function()
    it("has default empty slots", function()
        local items = ItemSystem.new()
        assert.is_nil(items.slots.Weapon)
    end)

    it("equips an item in a slot", function()
        local items = ItemSystem.new()
        items:equip("Weapon", "Sword")
        assert.equals("Sword", items.slots.Weapon)
    end)

    it("unequips an item and returns it", function()
        local items = ItemSystem.new()
        items:equip("Hat", "Cap")
        local removed = items:unequip("Hat")
        assert.equals("Cap", removed)
        assert.is_nil(items.slots.Hat)
    end)

    it("errors when using an invalid slot", function()
        local items = ItemSystem.new()
        assert.has_error(function()
            items:equip("Invalid", "Thing")
        end)
        assert.has_error(function()
            items:unequip("Invalid")
        end)
    end)
end)
