local ItemSystem = require("src.ItemSystem")

describe("ItemSystem", function()
    it("has default empty slots", function()
        local items = ItemSystem.new()
        assert.is_nil(items.slots.Weapon)
    end)

    it("equips an item in a slot", function()
        local items = ItemSystem.new()
        items:equip("Weapon", {name = "Sword"})
        assert.equals("Sword", items.slots.Weapon.name)
    end)

    it("unequips an item and returns it", function()
        local items = ItemSystem.new()
        items:equip("Hat", {name = "Cap"})
        local removed = items:unequip("Hat")
        assert.equals("Cap", removed.name)
        assert.is_nil(items.slots.Hat)
    end)

    it("upgrades an item when enough currency", function()
        local items = ItemSystem.new()
        items:equip("Weapon", {name = "Sword"})
        local ok = items:upgradeItem("Weapon", 1, 1)
        assert.is_true(ok)
        assert.equals(2, items.slots.Weapon.level)
    end)

    it("fails upgrade without sufficient currency", function()
        local items = ItemSystem.new()
        items:equip("Weapon", {name = "Sword"})
        local ok = items:upgradeItem("Weapon", 1, 0)
        assert.is_false(ok)
        assert.equals(1, items.slots.Weapon.level)
    end)

    it("errors when using an invalid slot", function()
        local items = ItemSystem.new()
        assert.has_error(function()
            items:equip("Invalid", {name = "Thing"})
        end)
        assert.has_error(function()
            items:unequip("Invalid")
        end)
    end)
end)
