local InventoryUISystem = require("src.InventoryUISystem")
local PlayerInputSystem = require("src.PlayerInputSystem")
local ItemSystem = require("src.ItemSystem")

describe("PlayerInputSystem", function()
    it("toggles inventory on B press", function()
        local items = ItemSystem.new()
        local ui = InventoryUISystem.new(items)
        local input = PlayerInputSystem.new(ui)
        local UIS = game:GetService("UserInputService")
        UIS._callback({KeyCode = Enum.KeyCode.B}, false)
        assert.is_true(ui._open)
    end)
end)
