local SkillTreeSystem = require("src.SkillTreeSystem")
local SkillSystem = require("src.SkillSystem")
local CurrencySystem = require("src.CurrencySystem")

describe("SkillTreeSystem", function()
    before_each(function()
        CurrencySystem.balances = {ether = 10}
    end)

    it("chooses a branch and applies upgrades", function()
        local ss = SkillSystem.new()
        ss:addSkill({name = "Fireball", rarity = "A"})
        local tree = SkillTreeSystem.new(ss)
        local ok = tree:chooseBranch(1, "power")
        assert.is_true(ok)
        assert.equals("power", ss.skills[1].branch)
        tree:upgradeSkill(1, 5)
        assert.is_true(ss.skills[1].damage >= 5)
    end)

    it("prevents choosing a second branch", function()
        local ss = SkillSystem.new()
        ss:addSkill({name = "Fireball", rarity = "A"})
        local tree = SkillTreeSystem.new(ss)
        tree:chooseBranch(1, "power")
        local ok = tree:chooseBranch(1, "rapid")
        assert.is_false(ok)
        assert.equals("power", ss.skills[1].branch)
    end)
end)
