return {
    Hat = {
        {name = "Cloth Cap", rarity = "C", slot = "Hat", stats = {health = 5, attackSpeed = 0.05}},
        {name = "Tattered Hood", rarity = "D", slot = "Hat", stats = {health = 3}},
        {name = "Wizard Hat", rarity = "B", slot = "Hat", stats = {magic = 4, attackSpeed = 0.1}},
        {name = "Mage Hat", rarity = "A", slot = "Hat", stats = {magic = 3}},
        {name = "Royal Crown", rarity = "S", slot = "Hat", stats = {health = 15}},
        {name = "Ancient Halo", rarity = "SS", slot = "Hat", stats = {magic = 10}},
        {name = "Eternal Halo", rarity = "SSS", slot = "Hat", stats = {magic = 20}},
    },
    Necklace = {
        {name = "Bronze Necklace", rarity = "C", slot = "Necklace", stats = {health = 2}},
        {name = "Silver Pendant", rarity = "D", slot = "Necklace", stats = {health = 3}},
        {name = "Amulet of Power", rarity = "B", slot = "Necklace", stats = {attack = 2}},
        {name = "Silver Necklace", rarity = "B", slot = "Necklace", stats = {health = 5}},
        {name = "Ruby Pendant", rarity = "A", slot = "Necklace", stats = {magic = 3}},
        {name = "Dragon Necklace", rarity = "S", slot = "Necklace", stats = {attack = 5}},
        {name = "Eternal Pendant", rarity = "SS", slot = "Necklace", stats = {magic = 8}},
        {name = "Cosmic Relic", rarity = "SSS", slot = "Necklace", stats = {magic = 16}},
    },
    Ring = {
        {name = "Simple Ring", rarity = "C", slot = "Ring", stats = {attack = 1}},
        {name = "Iron Band", rarity = "D", slot = "Ring", stats = {defense = 1}},
        {name = "Ruby Ring", rarity = "B", slot = "Ring", stats = {attack = 2}},
        {name = "Silver Ring", rarity = "B", slot = "Ring", stats = {attack = 2}},
        {name = "Mage Ring", rarity = "A", slot = "Ring", stats = {magic = 2}},
        {name = "Shadow Ring", rarity = "S", slot = "Ring", stats = {attack = 6}},
        {name = "Astral Ring", rarity = "SS", slot = "Ring", stats = {magic = 9}},
        {name = "Infinity Ring", rarity = "SSS", slot = "Ring", stats = {magic = 18}},
        {name = "Platinum Ring", rarity = "S", slot = "Ring", stats = {critDamage = 0.2}},
    },
    Armor = {
        {name = "Leather Armor", rarity = "C", slot = "Armor", stats = {health = 10}},
        {name = "Worn Mail", rarity = "D", slot = "Armor", stats = {health = 6}},
        {name = "Chain Mail", rarity = "B", slot = "Armor", stats = {defense = 3}},
        {name = "Knight Armor", rarity = "B", slot = "Armor", stats = {defense = 4}},
        {name = "Wizard Robe", rarity = "A", slot = "Armor", stats = {magic = 4}},
        {name = "Golden Armor", rarity = "A", slot = "Armor", stats = {defense = 8}},
        {name = "Dragon Scale", rarity = "S", slot = "Armor", stats = {defense = 15}},
        {name = "Celestial Plate", rarity = "SS", slot = "Armor", stats = {health = 25}},
        {name = "Eternal Guard", rarity = "SSS", slot = "Armor", stats = {defense = 35}},
    },
    Accessory = {
        {name = "Traveler's Brooch", rarity = "C", slot = "Accessory", stats = {speed = 0.05}},
        {name = "Old Trinket", rarity = "D", slot = "Accessory", stats = {health = 1}},
        {name = "Lucky Charm", rarity = "B", slot = "Accessory", stats = {critChance = 0.05}},
        {name = "Magic Charm", rarity = "A", slot = "Accessory", stats = {manaRegen = 0.1}},
        {name = "Healing Pendant", rarity = "B", slot = "Accessory", stats = {healthRegen = 0.5}},
        {name = "Winged Emblem", rarity = "A", slot = "Accessory", stats = {speed = 0.1}},
        {name = "Spirit Token", rarity = "S", slot = "Accessory", stats = {critChance = 0.1}},
        {name = "Ancient Talisman", rarity = "SS", slot = "Accessory", stats = {magic = 12}},
        {name = "Divine Sigil", rarity = "SSS", slot = "Accessory", stats = {magic = 24}},
    },
    Weapon = {
        {name = "Wooden Sword", rarity = "C", slot = "Weapon", stats = {attack = 3}},
        {name = "Rusty Blade", rarity = "D", slot = "Weapon", stats = {attack = 2}},
        {name = "Knight Sword", rarity = "B", slot = "Weapon", stats = {attack = 5}},
        {name = "Great Axe", rarity = "A", slot = "Weapon", stats = {attack = 8}},
        {name = "Longsword", rarity = "A", slot = "Weapon", stats = {attack = 7}},
        {name = "Legendary Sword", rarity = "S", slot = "Weapon", stats = {attack = 12}},
        {name = "Phoenix Claw", rarity = "S", slot = "Weapon", stats = {attack = 12}},
        {name = "Void Edge", rarity = "SS", slot = "Weapon", stats = {attack = 20}},
        {name = "Mythic Blade", rarity = "SS", slot = "Weapon", stats = {attack = 20}},
        {name = "Omega Breaker", rarity = "SSS", slot = "Weapon", stats = {attack = 40}},
    },
}
