return {
    {
        name = "Meadow",
        coordinates = {x = 0, y = 0, z = 0},
        placeId = 0,
        levelStart = 1,
        levelEnd = 30,
        floors = 30,
        bosses = {
            [5] = "Goblin Chief",
            [10] = "Ogre Brute",
            [30] = "Forest Dragon",
        },
        currency = "gold",
        theme = {
            windowBackground = {r = 25, g = 40, b = 25},
            buttonBackground = {r = 60, g = 90, b = 60},
            buttonHover = {r = 80, g = 120, b = 80},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(90, 110, 90) or {r=90,g=110,b=90},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(60, 80, 60) or {r=60,g=80,b=60},
            brightness = 2,
        },
    },
    {
        name = "Dungeon",
        coordinates = {x = 100, y = 0, z = 0},
        placeId = 0,
        levelStart = 31,
        levelEnd = 60,
        floors = 30,
        bosses = {
            [5] = "Skeleton Knight",
            [10] = "Dungeon Golem",
            [30] = "Lich King",
        },
        currency = "ore",
        theme = {
            windowBackground = {r = 30, g = 30, b = 45},
            buttonBackground = {r = 80, g = 50, b = 50},
            buttonHover = {r = 100, g = 70, b = 70},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(40, 40, 55) or {r=40,g=40,b=55},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(20, 20, 30) or {r=20,g=20,b=30},
            brightness = 1,
        },
    },
    {
        name = "Ruins",
        coordinates = {x = 200, y = 0, z = 0},
        placeId = 0,
        levelStart = 61,
        levelEnd = 90,
        floors = 30,
        bosses = {
            [5] = "Cursed Statue",
            [10] = "Ancient Guardian",
            [30] = "Ruined Titan",
        },
        currency = "crystal",
        theme = {
            windowBackground = {r = 45, g = 35, b = 25},
            buttonBackground = {r = 110, g = 70, b = 40},
            buttonHover = {r = 130, g = 90, b = 60},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(80, 70, 50) or {r=80,g=70,b=50},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(30, 30, 20) or {r=30,g=30,b=20},
            brightness = 1.5,
        },
    },
    {
        name = "Volcano",
        coordinates = {x = 300, y = 0, z = 0},
        placeId = 0,
        levelStart = 91,
        levelEnd = 120,
        floors = 30,
        bosses = {
            [5] = "Flame Knight",
            [10] = "Lava Behemoth",
            [30] = "Magma Lord",
        },
        currency = "crystal",
        theme = {
            windowBackground = {r = 70, g = 30, b = 30},
            buttonBackground = {r = 150, g = 60, b = 40},
            buttonHover = {r = 170, g = 80, b = 60},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(100, 60, 50) or {r=100,g=60,b=50},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(50, 30, 20) or {r=50,g=30,b=20},
            brightness = 2,
        },
    },
    {
        name = "Sky Castle",
        coordinates = {x = 400, y = 100, z = 0},
        placeId = 0,
        levelStart = 121,
        levelEnd = 150,
        floors = 30,
        bosses = {
            [5] = "Sky Knight",
            [10] = "Storm Dragon",
            [30] = "Celestial Emperor",
        },
        currency = "crystal",
        theme = {
            windowBackground = {r = 90, g = 90, b = 110},
            buttonBackground = {r = 160, g = 160, b = 200},
            buttonHover = {r = 180, g = 180, b = 220},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(120, 120, 150) or {r=120,g=120,b=150},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(90, 90, 120) or {r=90,g=90,b=120},
        brightness = 2,
        },
    },
    {
        name = "Abyss",
        coordinates = {x = 500, y = -50, z = 0},
        placeId = 0,
        levelStart = 151,
        levelEnd = 180,
        floors = 30,
        bosses = {
            [5] = "Abyss Guardian",
            [10] = "Void Horror",
            [30] = "Abyss Lord",
        },
        currency = "crystal",
        theme = {
            windowBackground = {r = 20, g = 20, b = 40},
            buttonBackground = {r = 60, g = 60, b = 100},
            buttonHover = {r = 80, g = 80, b = 120},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(10,10,20) or {r=10,g=10,b=20},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(5,5,10) or {r=5,g=5,b=10},
            brightness = 1.5,
        },
    },
    {
        name = "Underworld",
        coordinates = {x = 600, y = -100, z = 0},
        placeId = 0,
        levelStart = 181,
        levelEnd = 210,
        floors = 30,
        bosses = {
            [5] = "Hellhound",
            [10] = "Demon Lord",
            [30] = "Infernal King",
        },
        currency = "crystal",
        theme = {
            windowBackground = {r = 50, g = 20, b = 20},
            buttonBackground = {r = 100, g = 40, b = 40},
            buttonHover = {r = 120, g = 60, b = 60},
        },
        lighting = {
            ambient = Color3 and Color3.fromRGB and Color3.fromRGB(80,30,30) or {r=80,g=30,b=30},
            outdoorAmbient = Color3 and Color3.fromRGB and Color3.fromRGB(40,10,10) or {r=40,g=10,b=10},
            brightness = 2,
        },
    },
}
