return {
    {id = "kill_10", event = "EnemyKilled", goal = 10,
        reward = {currency = "gold", amount = 5, tickets = {skill = 1}}},
    {id = "kill_50", event = "EnemyKilled", goal = 50,
        reward = {currency = "gold", amount = 25, tickets = {skill = 3, equipment = 1}}},
    {id = "boss_slayer", event = "BossKilled", goal = 1,
        reward = {crystals = 10, tickets = {companion = 1}}},
    {id = "dungeon_master", event = "DungeonComplete", goal = 3,
        reward = {keys = {location = 1}}},
    {id = "first_raid", event = "RaidComplete", goal = 1,
        reward = {keys = {raid = 1}}},
    {id = "armor_breaker", event = "EnemyKilled", goal = 20,
        reward = {currency = "ore", amount = 10}},
    {id = "hundred_kills", event = "EnemyKilled", goal = 100,
        reward = {crystals = 5}},
    {id = "skill_master", event = "PlayerLevelUp", goal = 10,
        reward = {tickets = {skill = 5}}},
}
